name: Build and deploy GH Pages

## ref: https://github.com/peaceiris/actions-mdbook

on: 
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'mdbook/src/**'
      - 'mdbook/book.toml'
#      - 'In_One_Weekend/**'

  workflow_dispatch:

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v5
      # https://github.com/peaceiris/actions-mdbook
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
      - name: Build mdBook
        run: |
          cd mdbook/
          mdbook build
          touch ./book/.nojekyll
      # https://github.com/peaceiris/actions-gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mdbook/book